repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
-   repo: local
    hooks:
      -   id: dockerlint
          name: Dockerfile lint with hadolint
          description: Dockerfile lint with hadolint
          entry: hadolint/hadolint hadolint
          language: docker_image
          files: Dockerfile

